import type { Exercises, Workout } from './components/workouts-table/types'

export const exercises: Exercises = {
  exercise1: { name: 'Muscle Up', sets: [5, 4, 4, 3, 2] },
  exercise2: { name: 'Bulgarian Squats', sets: [8, 8, 8, 8] },
  exercise3: { name: 'Bar Dips', sets: [12, 10, 10, 8] },
  exercise4: { name: 'Wide Pull Up', sets: [8, 8, 7, 6] },
  exercise5: { name: 'Triceps Extensions', sets: [12, 10, 10, 8] },
  exercise6: { name: 'Windshield Wipers', sets: [12, 12, 10, 10] },
}

export const workouts: Workout[] = [
  {
    id: '0',
    name: 'Push Up Monday',
    description: 'good weather, good workout',
    totalReps: '97',
    week: '3',
    date: '15.01.2023',
    duration: '60',
    exercises,
  },
  {
    id: '1',
    name: 'FBW Thursday',
    description: 'muscle pains, bad weather',
    totalReps: '67',
    week: '2',
    date: '11.01.2023',
    duration: '75',
    exercises,
  },
  {
    id: '2',
    name: 'Pull Up Tuesday',
    description: 'record broken!!!',
    totalReps: '105',
    week: '2',
    date: '09.01.2023',
    duration: '45',
    exercises,
  },
  {
    id: '3',
    name: 'Push Up Monday',
    description: 'overall very good workout',
    totalReps: '80',
    week: '2',
    date: '08.01.2023',
    duration: '60',
    exercises,
  },
  {
    id: '4',
    name: 'Back + Arms',
    description: 'good weather, good workout',
    totalReps: '97',
    week: '1',
    date: '06.01.2023',
    duration: '60',
    exercises,
  },
  {
    id: '5',
    name: 'FBW Thursday',
    description: 'muscle pains, bad weather',
    totalReps: '67',
    week: '1',
    date: '04.01.2023',
    duration: '75',
    exercises,
  },
  {
    id: '6',
    name: 'Pull Up Tuesday',
    description: 'record broken!!!',
    totalReps: '105',
    week: '1',
    date: '02.01.2023',
    duration: '45',
    exercises,
  },
  {
    id: '7',
    name: 'Push Up Monday',
    description: 'overall very good workout',
    totalReps: '80',
    week: '1',
    date: '01.01.2023',
    duration: '60',
    exercises,
  },
]
