import type { Workout } from './components/workouts-table/types'

export const workouts: Workout[] = [
  {
    id: '0',
    name: 'Push Up Monday',
    description: 'good weather, good workout',
    totalReps: '97',
    week: '3',
    date: '15.01.2023',
    duration: '60',
  },
  {
    id: '1',
    name: 'FBW Thursday',
    description: 'muscle pains, bad weather',
    totalReps: '67',
    week: '2',
    date: '11.01.2023',
    duration: '75',
  },
  {
    id: '2',
    name: 'Pull Up Tuesday',
    description: 'record broken!!!',
    totalReps: '105',
    week: '2',
    date: '09.01.2023',
    duration: '45',
  },
  {
    id: '3',
    name: 'Push Up Monday',
    description: 'overall very good workout',
    totalReps: '80',
    week: '2',
    date: '08.01.2023',
    duration: '60',
  },
  {
    id: '4',
    name: 'Back + Arms',
    description: 'good weather, good workout',
    totalReps: '97',
    week: '1',
    date: '06.01.2023',
    duration: '60',
  },
  {
    id: '5',
    name: 'FBW Thursday',
    description: 'muscle pains, bad weather',
    totalReps: '67',
    week: '1',
    date: '04.01.2023',
    duration: '75',
  },
  {
    id: '6',
    name: 'Pull Up Tuesday',
    description: 'record broken!!!',
    totalReps: '105',
    week: '1',
    date: '02.01.2023',
    duration: '45',
  },
  {
    id: '7',
    name: 'Push Up Monday',
    description: 'overall very good workout',
    totalReps: '80',
    week: '1',
    date: '01.01.2023',
    duration: '60',
  },
]
